### ISSUE TITLE
a bug when run after 2 hours 

### ISSUE THREAD

**Issue by andyhebear** [i-e-b/DiskQueue#20] opened 2022-11-29 10:54 UTC
System.InvalidOperationException
  HResult=0x80131509
  Message=End of file reached while trying to read queue item. Exceeded retry count.
  Source=DiskQueue
  StackTrace:
   at DiskQueue.Implementation.PersistentQueueImpl.ReadAhead() in C:\gits\DiskQueue\src\DiskQueue\Implementation\PersistentQueueImpl.cs:line 378
   at DiskQueue.Implementation.PersistentQueueImpl.Dequeue() in C:\gits\DiskQueue\src\DiskQueue\Implementation\PersistentQueueImpl.cs:line 335
   at DiskQueue.Implementation.PersistentQueueSession.Dequeue() in C:\gits\DiskQueue\src\DiskQueue\Implementation\PersistentQueueSession.cs:line 130
   at MyQueueDisk`1.Peek() in MyQueueDisk.cs:line 54
   at OJ.Worker.OJWorker.WorkThread() in IWorker.cs:line 131

  此异常最初是在此调用堆栈中引发的: 
    DiskQueue.Implementation.PersistentQueueImpl.ReadAhead() (位于 PersistentQueueImpl.cs 中)
    DiskQueue.Implementation.PersistentQueueImpl.Dequeue() (位于 PersistentQueueImpl.cs 中)
    DiskQueue.Implementation.PersistentQueueSession.Dequeue() (位于 PersistentQueueSession.cs 中)
    MyQueueDisk<T>.Peek() (位于 MyQueueDisk.cs 中)
    OJ.Worker.OJWorker.WorkThread() (位于 IWorker.cs 中)

**Comment by i-e-b** [comment] 2022-12-01 09:57
Closing as duplicate of #21

**Closed as completed by i-e-b** 2022-12-01 09:57 UTC
