### ISSUE TITLE
a bug when run after 2 hours 

### ISSUE THREAD

**Issue by andyhebear** [i-e-b/DiskQueue#21] opened 2022-11-29 10:54 UTC
using v 1.6.0 

System.InvalidOperationException
  HResult=0x80131509
  Message=End of file reached while trying to read queue item. Exceeded retry count.
  Source=DiskQueue
  StackTrace:
   at DiskQueue.Implementation.PersistentQueueImpl.ReadAhead() in C:\gits\DiskQueue\src\DiskQueue\Implementation\PersistentQueueImpl.cs:line 378
   at DiskQueue.Implementation.PersistentQueueImpl.Dequeue() in C:\gits\DiskQueue\src\DiskQueue\Implementation\PersistentQueueImpl.cs:line 335
   at DiskQueue.Implementation.PersistentQueueSession.Dequeue() in C:\gits\DiskQueue\src\DiskQueue\Implementation\PersistentQueueSession.cs:line 130
   at MyQueueDisk`1.Peek() in MyQueueDisk.cs:line 54
   at OJ.Worker.OJWorker.WorkThread() in IWorker.cs:line 131

  此异常最初是在此调用堆栈中引发的: 
    DiskQueue.Implementation.PersistentQueueImpl.ReadAhead() (位于 PersistentQueueImpl.cs 中)
    DiskQueue.Implementation.PersistentQueueImpl.Dequeue() (位于 PersistentQueueImpl.cs 中)
    DiskQueue.Implementation.PersistentQueueSession.Dequeue() (位于 PersistentQueueSession.cs 中)
    MyQueueDisk<T>.Peek() (位于 MyQueueDisk.cs 中)
    OJ.Worker.OJWorker.WorkThread() (位于 IWorker.cs 中)

**Comment by andyhebear** [comment] 2022-11-29 11:05
[WorkerQueue.dat.zip](https://github.com/i-e-b/DiskQueue/files/10112380/WorkerQueue.dat.zip)
this file is diskqueue generate
public class MyQueueDisk<T> : IMyQueue<T>, IDisposable {
        IPersistentQueue m_dq;
        IMySerializer m_ser;
        public MyQueueDisk(string path, IMySerializer serializer) {
            m_dq = new PersistentQueue(path,1024*1024*2);
            m_ser = serializer;

        }
        public void Clear() {
            m_dq.HardDelete(true);

        }

        public T Dequeue() {
            using (var session = m_dq.OpenSession()) {
                var data = session.Dequeue();
                if (data != null) {
                    session.Flush();
                    return m_ser.Deserialize<T>(data);
                }
                throw new InvalidOperationException("队列为空");
            }
        }

        public void Dispose() {
            m_dq.Dispose();
        }

        public void Enqueue(T item) {
            using (var session = m_dq.OpenSession()) {
                session.Enqueue(m_ser.SerializeToBin(item));
                session.Flush();

            }
        }

        public int GetCount() {
            return m_dq.EstimatedCountOfItemsInQueue;

        }

        public T Peek() {
            using (var session = m_dq.OpenSession()) {
                var d = session.Dequeue();
                if (d != null) {
                    return m_ser.Deserialize<T>(d);
                }
                else {
                    throw new InvalidOperationException("队列为空");
                }
            }
        }
    }

**Comment by andyhebear** [comment] 2022-11-29 11:11
a thread enqueue generate data like:
        private void debugGenerateMsg() {
#if DEBUG_Test
            while (true) {
                System.Threading.Thread.Sleep(50);
                var Request =...
                lock (m_lock) {                   
                    m_queue.Enqueue(Request );
                }
            }
#endif
        }

a thread read:
Request req;                
                    lock (m_lock) {
                        if (m_queue.GetCount() > 0) {
                         
                            req = m_queue.Peek();
                           
                        }
                       if(req!=null){
//do something
...
                           lock (m_lock) {
                          System.Threading.Thread.Sleep(10);
                            req = m_queue.Dequeue();
                            //System.Threading.Thread.Sleep(1000);
                            
                        }
}
                    }

**Comment by andyhebear** [comment] 2022-11-29 11:47
产生错误后，执行  m_queue.Clear(); 下次启动必须删除transaction.log与lock文件，否则继续报错,
即使设置 m_dq.Internals.AllowTruncatedEntries = true 也不行。
[transaction.log](https://github.com/i-e-b/DiskQueue/files/10112997/transaction.log)

**Comment by i-e-b** [comment] 2022-11-30 14:58
Hello.

Sorry. This is a problem that happens with some file systems. As far as I can tell, this is caused by a bug in Windows.

If you are using a different operating system, please let me know.

谷歌翻译

你好。

对不起。 这是某些文件系统会发生的问题。 据我所知，这是由 Windows 中的错误引起的。

如果您使用不同的操作系统，请告诉我。

**Comment by andyhebear** [comment] 2022-12-07 02:57
版本	Windows 10 专业版
版本号	22H2
安装日期	‎2022/‎11/‎18
操作系统内部版本	19045.2251
体验	Windows Feature Experience Pack 120.2212.4180.0

**Comment by i-e-b** [comment] 2022-12-07 08:26
Thank you for the information.
Can you please try version 1.6.2 and tell me if the problem is still there?

谷歌翻译

感谢您的信息。
你能不能试试 1.6.2 版本，然后告诉我问题是否仍然存在？

https://www.nuget.org/packages/DiskQueue/1.6.2

**Comment by i-e-b** [comment] 2022-12-19 09:18
I will close this issue report now.
Please let me know if you have any further information.

谷歌翻译

我将关闭此报告。
如果您有任何其他信息，请重新打开报告。

**Closed as completed by i-e-b** 2022-12-19 09:18 UTC
