### ISSUE TITLE
End of file reached while trying to read queue item

### ISSUE THREAD

**Issue by Juulbl** [i-e-b/DiskQueue#15] opened 2021-11-30 13:44 UTC
We are using DiskQueue version 1.3.2 in a C# Windows service application that is running on Windows 7 and Windows 10. 
In this application, we are using DiskQueue as a buffer for communication protocols, where every item that needs to be sent will be queued, and another part of the code dequeues and sends these items. After running this application for a long time we received the "End of file reached while trying to read queue item" exception as shown below.

```
System.InvalidOperationException: End of file reached while trying to read queue item
at DiskQueue.Implementation.PersistentQueueImpl.ReadEntriesFromFile(Entry firstEntry, Int64 currentBufferSize)
at DiskQueue.Implementation.PersistentQueueImpl.ReadAhead()
at DiskQueue.Implementation.PersistentQueueImpl.Dequeue()
at DiskQueue.Implementation.PersistentQueueSession.Dequeue()
```

The enqueuing of items happens roughly every second, and dequeuing is done continuously while items are queued. Both of these actions run in their own Tasks and queue sessions are opened and closed with each operation.

Although the same exception was described in issue #13, our application buffer contains a `data.663` that does not contain any data and was not manually altered.

Is there a way to avoid this issue and/or is there a way to just ignore files like the `data.663` while continuing to use the buffer?

**Comment by i-e-b** [comment] 2021-11-30 17:48
As a temporary fix, you should be able to use `queue.Internals.AllowTruncatedEntries = true;` to skip these errors.
If that doesn't work, please let me know.

**Comment by smitsr72** [comment] 2022-03-14 15:35
The issue described by juulbl still occurs. 

We get the below exception first, which suggests that a session is still open by the producer thread, while the consumer thread (this one) is trying to dequeue.

Error processing persistent queue for MQTT endpoint.|[System.IO](http://system.io/).IOException: The process cannot access the file 'D:\AI-Data\DataServiceR3\IoTHubQueue\data.167' because it is being used by another process.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.File.InternalDelete(String path, Boolean checkHost)
at System.IO.File.Delete(String path)
at DiskQueue.Implementation.PersistentQueueImpl.ApplyTransactionOperations(IEnumerable1 operations)    at DiskQueue.Implementation.PersistentQueueImpl.CommitTransaction(ICollection1 operations)
at DiskQueue.Implementation.PersistentQueueSession.Flush()
at AI.MetalFAB1.DataRouter.Collections.PersistentQueue.Dequeue()
at AI.MetalFAB1.DataRouter.Endpoints.IotHub.IoTHubClient.<ProcessNextPersistentQueueItemAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at AI.MetalFAB1.DataRouter.Endpoints.IotHub.IoTHubClient.<ProcessPersistentQueueItemsAsync>d__22.MoveNext()

After this happened we get lot of the following exceptions:

Error processing persistent queue for MQTT endpoint.|System.InvalidOperationException: End of file reached while trying to read queue item
at DiskQueue.Implementation.PersistentQueueImpl.ReadEntriesFromFile(Entry firstEntry, Int64 currentBufferSize)
at DiskQueue.Implementation.PersistentQueueImpl.ReadAhead()
at DiskQueue.Implementation.PersistentQueueImpl.Dequeue()
at DiskQueue.Implementation.PersistentQueueSession.Dequeue()
at AI.MetalFAB1.DataRouter.Collections.PersistentQueue.Peek()
at AI.MetalFAB1.DataRouter.Endpoints.IotHub.IoTHubClient.<ProcessNextPersistentQueueItemAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at AI.MetalFAB1.DataRouter.Endpoints.IotHub.IoTHubClient.<ProcessPersistentQueueItemsAsync>d__22.MoveNext()

It seems that the first exception is the cause of the 0 kb file, and the subsequent dequeue calls are not able to read past the 0 kb file. The latter should be fixable by the queue.Internals.AllowTruncatedEntries = true;. I will try that.

I do have a question on the usage. For producing items we do openSession, enqueue and flush. For consuming we do a peek (opensession and dequeue, but not a flush), then we try an deliver the data over the network (which may fail), when successful we do a proper dequeue with flush. We do not do any locking between producer and consumer tasks, because we assume this is handled by the DiskQueue. Is that assumption correct or do you expect us to mutually exclude the producer and consumer threads.

**Comment by i-e-b** [comment] 2022-03-14 19:37
Thanks for the extra details. I'll take a look when I can.

> I do have a question on the usage. For producing items we do openSession, enqueue and flush. For consuming we do a peek (opensession and dequeue, but not a flush), then we try an deliver the data over the network (which may fail), when successful we do a proper dequeue with flush. We do not do any locking between producer and consumer tasks, because we assume this is handled by the DiskQueue. Is that assumption correct or do you expect us to mutually exclude the producer and consumer threads.

Your usage is correct. You should not have to co-ordinate between producers and consumers.
This library *does* rely on the underlying filesystem, so any bugs there will have an effect on DiskQueue,

**Comment by i-e-b** [comment] 2022-03-16 14:29
https://www.nuget.org/packages/DiskQueue/1.4.0

Version 1.4.0 has some increased strictness around locking and deleting files. This will hopefully prevent overlapping access as much as possible.

There is now a global setting to skip errors in the case of truncated files:
`PersistentQueue.DefaultSettings.AllowTruncatedEntries = true;`
That should be set before creating queue instances.

If you have any further issues, please provide any details that you can.

**Comment by smitsr72** [comment] 2022-03-17 07:50
Thanks for the update Ian. I will integrate this version and test it. I'll keep you updated. Sometimes it takes over a week for the issue to occur. Patience is needed to conclude if the issue is solved.

**Comment by i-e-b** [comment] 2022-03-21 08:01
I've managed to find a semi-reliable way to trigger this. Seems to happen with Docker images.
Can confirm that the issue still exists.

**Comment by smitsr72** [comment] 2022-03-21 10:00
At our side we did not manage to reproduce yet. Duration test still running.

**Comment by smitsr72** [comment] 2022-03-24 06:50
The issue reproduced. 

```
2022-03-23 15:12:07.0451|ERROR|AI.MetalFAB1.DataRouter.Endpoints.Mqtt.MQTTEndpoint|Error processing persistent queue for MQTT endpoint.|System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at DiskQueue.Implementation.FileOperations.PrepareDelete(String path)
   at DiskQueue.Implementation.PersistentQueueImpl.ApplyTransactionOperations(IEnumerable`1 operations)
   at DiskQueue.Implementation.PersistentQueueImpl.CommitTransaction(ICollection`1 operations)
   at DiskQueue.Implementation.PersistentQueueSession.Flush()
   at AI.MetalFAB1.DataRouter.Collections.PersistentQueue.Dequeue()
   at AI.MetalFAB1.DataRouter.Endpoints.Mqtt.MQTTEndpoint.<ProcessNextPersistentQueueItemAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AI.MetalFAB1.DataRouter.Endpoints.Mqtt.MQTTEndpoint.<ProcessPersistentQueueItemsAsync>d__19.MoveNext()
```

There is a 0kb data file on disk. It seems we cannot read past the 0kb file. The setting PersistentQueue.DefaultSettings.AllowTruncatedEntries = true; did not allow us to read part is issue.

**Comment by i-e-b** [comment] 2022-03-25 12:06
Thanks for the info. I'm going to re-work the file handling, as I think there must be a race in the File API to cause this.

**Comment by i-e-b** [comment] 2022-04-06 17:11
https://www.nuget.org/packages/DiskQueue/1.5.0

Version 1.5.0 has completely re-written low level file access classes.
Please try this, and feed back any results (good or bad).

Many thanks for your patience!

**Comment by i-e-b** [comment] 2022-05-31 15:17
I'm going to close this issue for now.
If anyone encounters it again with DiskQueue 1.5.0 or later, please feel free to re-open

**Closed as completed by i-e-b** 2022-05-31 15:17 UTC
